### ISSUE TITLE
ENDPOINT: Edit Book's Info

### ISSUE THREAD

**Issue by David-Egan** [njb5081/SWEN-344-API#13]
Parameters: all the book info

**In progress by Kaitlin**

**Comment by kmb4577** [comment]
How do I assign myself to this one?

**Comment by David-Egan** [comment]
You need to accept Nick's invite to be a collaborator first.  It should be in your email or somewhere else on Github.

**Comment by kmb4577** [comment]
oh ok, thanks!

**Comment by David-Egan** [comment]
Looks good just needs some testing with the JS framework
